version: 0.2

phases:
    install:
        runtime-versions:
            dotnet: latest
    build:
        commands:
            - dotnet build -c Release ./dotnetgithubactionscode/dotnetgithubactionscode.csproj
            - dotnet test -c Release ./dotnetGithubactionscode.test/dotnetGithubactionscode.test.csproj

artifacts: 
     files:
      - ./**/*
      - .ebextensions/**/*
 