version: 0.2

phases:
    install:
        runtime-versions:
            dotnet: latest
    build:
        commands:
            - dotnet build -c Release --no-restore
            - dotnet test -c Release --no-build